#!/usr/bin/env python3
"""Provide complete core resources through NetSurf's native direct-data API."""
from pathlib import Path
import sys

res = Path(sys.argv[1])
out = Path(sys.argv[2])
names = ('default.css', 'quirks.css', 'internal.css', 'adblock.css',
         'welcome.html', 'credits.html', 'licence.html', 'netsurf.png')
entries = []
text = ['/* Generated by embed_netsurf_resources.py. Original NetSurf resources. */']
for i, name in enumerate((*names, 'user.css')):
    data = b'\n' if name == 'user.css' else (res / name).read_bytes()
    if not data:
        raise SystemExit(f'Empty resource: {name}')
    text.append(f'static const uint8_t ps4_res_{i}[] = {{')
    for start in range(0, len(data), 20):
        text.append(','.join(str(n) for n in data[start:start + 20]) + ',')
    text.append('};')
    entries.append(f'    {{"{name}", ps4_res_{i}, sizeof(ps4_res_{i})}},')
text += ['struct ps4_resource { const char *name; const uint8_t *bytes; size_t size; };',
         'static const struct ps4_resource ps4_resources[] = {', *entries, '};',
         '''static nserror ps4_get_resource_data(const char *path,
        const uint8_t **data, size_t *len)
{
    for (size_t i = 0; i < sizeof(ps4_resources)/sizeof(ps4_resources[0]); i++) {
        if (strcmp(path, ps4_resources[i].name) == 0) {
            *data = ps4_resources[i].bytes;
            *len = ps4_resources[i].size;
            return NSERROR_OK;
        }
    }
    return NSERROR_NOT_FOUND;
}
static nserror ps4_release_resource_data(const uint8_t *data)
{
    (void)data; /* Static storage lives for the whole process. */
    return NSERROR_OK;
}
''']
out.write_text('\n'.join(text))
